# Generated by Django 2.1.5 on 2019-01-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updateddatetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
