# Generated by Django 2.1.5 on 2019-01-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190116_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datetime',
            new_name='createddatetime',
        ),
    ]
