# Generated by Django 2.1.5 on 2019-01-16 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updateddatetime',
        ),
    ]
