# Generated by Django 2.1.5 on 2019-01-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_updateddatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentdatetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='createddatetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
